import { Agility } from "../../BattleAttributes/Agility";
import { CurrentHealth } from "../../BattleAttributes/CurrentHealth/CurrentHealth";
import { Damage } from "../../BattleAttributes/Damage";
import { Defense } from "../../BattleAttributes/Defense";
import { Energy } from "../../BattleAttributes/Energy";
import { Resistance } from "../../BattleAttributes/Resistance";
import { Spell } from "../../BattleAttributes/Spell";
import { Level } from "../../LevelAttributes/Level";
import { NeededExperience } from "../../LevelAttributes/NeededExperience";
import { TotalExperience } from "../../LevelAttributes/TotalExperience";
import { Dextery } from "../../PrimaryAttributes/Dextery";
import { Intelligence } from "../../PrimaryAttributes/Intelligence";
import { MaxHealth } from "../../PrimaryAttributes/MaxHealth";
import { Strength } from "../../PrimaryAttributes/Strength";

export type BaseAttributeModelOld = {
  Strength: Strength;
  Dextery: Dextery;
  Intelligence: Intelligence;
  MaxHealth: MaxHealth;
  CurrentHealth: CurrentHealth;
  Agility: Agility;
  Damage: Damage;
  Defense: Defense;
  Energy: Energy;
  Resistance: Resistance;
  Spell: Spell;
  Level: Level;
  NeededExperience: NeededExperience;
  TotalExperience: TotalExperience;
};
